### ISSUE TITLE
Custom selector for append

### ISSUE THREAD

**Issue by dtelaroli** [bdparrish/cytoscape.js-toolbar#4]
Thanks for that.

I need configure the container to append the tools.
Now, it's append to body, but I use tabs and it's showing in both, because use absolute style.

**Comment by bdparrish** [comment]
The `body` element is only used to get the toolbar to the page.  The `zIndex` option is used to determine depth in page.  If you are using tabs then you should dynamically set the `visibility` or `hidden` when the event fires to switch tabs.

**Comment by dtelaroli** [comment]
It's a bad workaround, because broke my responsive layout.
But ok, thanks for the extension.

**Comment by ben-humangeo** [comment]
You have one specific design that involves a responsiveness. I am not sure how this will effect it.  And this isn't a workaround.  It involves you dynamically showing or hiding an element on a page based on state.  How else would you do it?  Also the zIndex value is defaulted to 9999.  If you would like to submit a PR, then I would be happy to take a look.
